### ISSUE TITLE
Required Feature: Config-class

### ISSUE THREAD

**Issue by skx** [skx/lumail2#1]
A lot of lumail configuration comes down to handling configuration variables. e.g:

      maildir_prefix( "~/Maildir" )
      headers = { "To", "From", "Subject" }

We need a config class that will get/set these values.  Instead of just strings we should also allow get/set of tables (at least string arrays with numerical indexes) such as:

    Config:get( "maildir_prefix" )
    Config:get( "message.headers" )

**Comment by jugglerchris** [comment]
Why not just use Lua tables?

**Comment by skx** [comment]
Because I expect most of the usage will be on the C-side, and I wanted that to be the simpler method.
